//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandLine.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpTextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpTextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandLine.Text.HelpTextStrings", typeof(HelpTextStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string AppTitleFormat {
            get {
                return ResourceManager.GetString("AppTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the option {0} ({1}) could not be parsed: {2}.
        /// </summary>
        internal static string BadValueFormatError {
            get {
                return ResourceManager.GetString("BadValueFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verb &apos;{0}&apos; is not recognized..
        /// </summary>
        internal static string BadVerbSelectedErrorFormat {
            get {
                return ResourceManager.GetString("BadVerbSelectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option {0} was specified multiple times, but does not support multiple values..
        /// </summary>
        internal static string DuplicateOptionErrorFormat {
            get {
                return ResourceManager.GetString("DuplicateOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        internal static string HelpOptionDescription {
            get {
                return ResourceManager.GetString("HelpOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display help for a specific command..
        /// </summary>
        internal static string HelpVerbDescription {
            get {
                return ResourceManager.GetString("HelpVerbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the option {0} ({1}) is not valid: {2}.
        /// </summary>
        internal static string InvalidValueErrorFormat {
            get {
                return ResourceManager.GetString("InvalidValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required option {0} was not specified..
        /// </summary>
        internal static string MissingRequiredOptionErrorFormat {
            get {
                return ResourceManager.GetString("MissingRequiredOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option {0} requires a value, but none was specified..
        /// </summary>
        internal static string MissingValueErrorFormat {
            get {
                return ResourceManager.GetString("MissingValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option(s) {0} cannot be used with the option(s) {1}..
        /// </summary>
        internal static string MutuallyExclusiveSetErrorFormat {
            get {
                return ResourceManager.GetString("MutuallyExclusiveSetErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb was specified..
        /// </summary>
        internal static string NoVerbSelectedErrorFormat {
            get {
                return ResourceManager.GetString("NoVerbSelectedErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: {0} - {1}.
        /// </summary>
        internal static string SelectedVerbFormat {
            get {
                return ResourceManager.GetString("SelectedVerbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; was not expected..
        /// </summary>
        internal static string UnexpectedValueErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option &apos;{0}&apos; was not recognized..
        /// </summary>
        internal static string UnknownOptionErrorFormat {
            get {
                return ResourceManager.GetString("UnknownOptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0} {1}.
        /// </summary>
        internal static string UsageStringFormat {
            get {
                return ResourceManager.GetString("UsageStringFormat", resourceCulture);
            }
        }
    }
}
